<a href="https://colab.research.google.com/github/Deep65/Data-Science-libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Numpy Library**

In [14]:
import numpy as np


**Some Basics**

In [13]:
a=np.array([2,5,45])
b=np.array([1,3,4])
a*b

array([  2,  15, 180])

In [34]:
c=np.array([[1,2,3],[4,5,5],[4,5,7]])
c
d=np.array([[1,3,4],[54,64,6],[45,12,1]])
e=np.array([[1,3,4],[54,64,6],[45,12,1]])
f=(c+d)*e

In [38]:
#get shape
a.shape

(3,)

In [39]:
#get dimension
d.ndim

2

In [41]:
#get type
a.dtype

dtype('int64')


**Accessing/Changing specific elements, rows, columns, etc**


In [67]:
a=np.array([[1,2,3,4,5],[5,6,7,8,9]])
a.shape

(2, 5)

In [68]:
a

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [69]:
# Get a specific element [r, c]
a[1,4]

9

In [70]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1,0:4:2]

array([5, 7])

In [71]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5])

In [73]:
# Get a specific column
a[:,4]

array([5, 9])


**3D example**


In [79]:
f=np.array([[[1,3],[34,54],[1,5]],[[1,3],[4,5],[1,2]]])

In [82]:
f

array([[[ 1,  3],
        [34, 54],
        [ 1,  5]],

       [[ 1,  3],
        [ 4,  5],
        [ 1,  2]]])

In [93]:
# Get specific element (work outside in)
f[0,1,0]

34

In [83]:
f.ndim

3

In [84]:
f.shape

(2, 3, 2)



```
# This is formatted as code
```


**Initializing Different Types of Arrays¶**



In [97]:
#All 0's *matrix*
q=np.zeros((3,3))
q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
#All 1's *matrix*
w=np.ones((40,88))
w

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])